### ISSUE TITLE
Prometheus Metrics Pushgateway Error Format Issue

### ISSUE THREAD

**Issue by timo102** [redpanda-data/connect#2835] opened 2024-09-05 16:55 UTC
Hello,

we are struggling to identify a problem with metrics and the Prometheus pushgateway, because the error is not correctly formatted. The important error message is hidden.

The configuration is:
```
metrics:
  prometheus:
    push_url: "http://localhost:9091"
    push_job_name: "anyname"
    add_process_metrics: true
```

The problem is very easy to reproduce by shutting the pushgateway down. So you don't need the pushgateway to reproduce the issue.

With an unavailable pushgateway, Redpanda Connect will print the following error message in the log line:
```
Failed to cleanly close observability components: %!w(*url.Error=\u0026{Put http://localhost:9091/metrics/job/anyname 0xc002434d70})
```

Expected is an error message with more details, for example:
```
Failed to cleanly close observability components: Put "http://localhost:9091/metrics/job/anyname": dial tcp [::1]:9091: connectex: No connection could be made because the target machine actively refused it.
```

The problem is that the format string `%w` seems to be used to print this error. The error message is coming from the Prometheus library "push" https://pkg.go.dev/github.com/prometheus/client_golang/prometheus/push and needs to be printed correctly.

**Comment by mihaitodor** [comment] 2024-09-05 17:39
Hey @timo102 👋 I believe this is likely a duplicate of #2754. I have a potential fix for it here https://github.com/redpanda-data/benthos/pull/66, but not sure when Ash will get a chance to have a look at it.

**Comment by mihaitodor** [comment] 2024-09-08 01:11
@timo102 Oops, my bad! I kind of assumed that, under the hood, `%w` is handled just like all the other verbs. Turns out it's only available for `fmt.Errorf()`, so the logger has no clue how to handle it... Thanks for pointing this issue out! Wish it was possible to detect it via linting, but that doesn't work when there are layers of indirection.

Should be fixed via https://github.com/redpanda-data/benthos/pull/87.

**Closed** 2024-09-11 12:40 UTC
Labels: bug, observability
